export const Data = [
  {
    id: 0,
    name: "Футболка gucci",
    price: 2400,
    img: "img/Gucci.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 2400,
    type: "t-shirt",
  },
  {
    id: 1,
    name: "Футболка Adidas",
    price: 500,
    img: "img/adidas.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 500,
    type: "t-shirt",
  },
  {
    id: 2,
    name: "Футболка-поло",
    price: 490,
    img: "img/polo.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 490,
    type: "t-shirt",
  },
  {
    id: 3,
    name: "Футболка Lacoste",
    price: 790,
    img: "img/lacoste.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 790,
    type: "t-shirt",
  },
  {
    id: 4,
    name: "Футболка-поло",
    price: 290,
    img: "img/music.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 290,
    type: "t-shirt",
  },
  {
    id: 5,
    name: "Футболка Mother of cats",
    price: 490,
    img: "img/cat.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 490,
    type: "t-shirt",
  },
  {
    id: 6,
    name: "Футболка Mickey Mouse",
    price: 390,
    img: "img/mickey.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 390,
    type: "t-shirt",
  },
  {
    id: 7,
    name: "Футболка спортивная",
    price: 490,
    img: "img/varathan-movie.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 490,
    type: "t-shirt",
  },
  {
    id: 8,
    name: "Футболка спортивная",
    price: 320,
    img: "img/chill.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 320,
    type: "t-shirt",
  },
  {
    id: 9,
    name: "Футболка Dope",
    price: 270,
    img: "img/dope.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 270,
    type: "t-shirt",
  },
  {
    id: 10,
    name: "Лонгслив",
    price: 3300,
    img: "img/fly.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 3300,
    type: "t-shirt",
  },
  {
    id: 11,
    name: "Футболка модная",
    price: 430,
    img: "img/gang.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 430,
    type: "t-shirt",
  },
  {
    id: 13,
    name: "Футболка спортивная TKY",
    price: 2100,
    img: "img/TKY CAMO TEE.jpeg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 2100,
    type: "t-shirt",
  },
  {
    id: 15,
    name: "Ветровка Gucci",
    price: 17000,
    img: "img/Coated cotton windbreaker with Gucci lable.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 17000,
    type: "jacket",
  },
  {
    id: 16,
    name: "Куртка Gucci",
    price: 14000,
    img: "img/Gucci Off The Grid zip-up.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 14000,
    type: "jacket",
  },
  {
    id: 17,
    name: "Штаны Gucci",
    price: 9800,
    img: "img/Coated cotton pant with Gucci label.jpg",
    description:
      "Enim nulla enim deserunt amet aute. Est veniam non duis excepteur ea fugiat et dolore. Minim nulla excepteur ut laborum sit sunt officia occaecat officia ex quis deserunt in dolor.Dolore cillum aute fugiat Lorem Lorem aliquip exercitation sunt minim officia ex minim sint. Dolore aliquip ut ullamco adipisicing exercitation nostrud amet reprehenderit tempor ea. Aliqua cupidatat nisi eu tempor labore nisi est quis ullamco. Fugiat adipisicing eiusmod quis ipsum veniam est elit proident enim velit fugiat mollit qui.",
    inCart: false,
    count: 1,
    total: 9800,
    type: "trouser",
  },
];

export const mainRange = [
  { startPrice: 30, endPrice: "or less" },
  { startPrice: 30, endPrice: 70 },
  { startPrice: 70, endPrice: 100 },
  { startPrice: 100, endPrice: "& Above" },
  { startPrice: 0, endPrice: "reset" },
];

export const productType = [
  "t-shirt",
  "jacket",
  "shoes",
  "trouser",
  "watch",
  "all",
];
